# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
jobs:
  app:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      #Backend
      - run: cp ../.env backend/.env
      - run: cd backend && npm i
      - run: cd backend && pm2 start start-server.js --name=notepadapp-backend
      #- run: pm2 restart notepadapp-backend

      #Frontend
      # - run: cd frontend && npm i && npm run build
      # - run: rm -rf /var/www/notepadapp/build
      # - run: cd frontend && mv build /var/www/notepadapp/build
